package com.eureckah.banking.tenants.domain.model;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Tenant {

    // TODO: should be autogenerated later
    private TenantId id;
    private String name;

    public Tenant(String name) {
        this.name = name;
    }
}
