site_name: Personal Banking — Docs
repo_url: https://example.com/your/repo
nav:
  - Overview: index.md
  - Architecture:
    - Context: architecture/c4-context.md
    - Containers: architecture/c4-container.md
    - ADRs Index: architecture/decisions/index.md
  - Contracts:
    - OpenAPI v1 Changelog: contracts/openapi/v1/CHANGELOG.md
#    - Events v1 Changelog: contracts/events/v1/CHANGELOG.md
  - Governance:
    - Scope CHANGELOG: governance/scope-CHANGELOG.md
    - Product CHANGELOG: governance/product-CHANGELOG.md
    - Security: governance/SECURITY.md
    - SLOs & SLIs: governance/SLOs-SLIs.md
theme:
  name: material
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - tables
  - footnotes
plugins:
  - search

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - assets/js/mermaid-init.js
