server:
  port: 8080

spring:
  application:
    name: api

grpc:
  client:
    tenants:
      address: "static://localhost:9090"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT
