server:
  port: 80

spring:
  application:
    name: api

  grpc:
    client:
      channels:
        tenants:
          address: "discovery:///tenants"
          enableKeepAlive: true
          keepAliveWithoutCalls: true
          negotiationType: PLAINTEXT

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
