package com.eureckah.banking.tenants.domain;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.util.UUID;

@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Profile {

    // TODO: should be autogenerated later
    private UUID id;
    private Tenant tenant;
    private User user;
    private Role role;
}
