package com.eureckah.banking.tenants.domain;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Profile {

    // TODO: should be autogenerated later
    private ProfileId id;
    private Tenant tenant;
    private User user;
    private Role role;

    public Profile(Tenant tenant, User user, Role role) {
        this.tenant = tenant;
        this.user = user;
        this.role = role;
    }

}
